### Pandas, part 2
There are many ways to achieve the same output with Pandas.  In this drill we review practice using world travel data from the The World Bank https://data.worldbank.org/indicator/ST.INT.ARVL.

First import this "travelData.csv" file and get to know the data.  
What are the columns and rows?

In [6]:
import pandas as pd
dataFile = pd.read_csv("travelData.csv")
dataFile

,Country_Name,Code,Indicator_Name,Ind_Code,1995,1996,1997,1998,1999,2000,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Aruba,ABW,"International tourism, number of arrivals",ST.INT.ARVL,619000.0,641000.0,650000.0,647000.0,683000.0,721000.0,...,772000.0,827000.0,813000.0,824000.0,869000.0,904000.0,979000.0,1072000.0,1225000.0,1102000.0
1,Afghanistan,AFG,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Angola,AGO,"International tourism, number of arrivals",ST.INT.ARVL,9000.0,21000.0,45000.0,52000.0,45000.0,51000.0,...,195000.0,294000.0,366000.0,425000.0,481000.0,528000.0,650000.0,595000.0,592000.0,397000.0
3,Albania,ALB,"International tourism, number of arrivals",ST.INT.ARVL,304000.0,287000.0,119000.0,184000.0,371000.0,317000.0,...,1062000.0,1247000.0,1711000.0,2191000.0,2469000.0,3156000.0,2857000.0,3341000.0,3784000.0,4070000.0
4,Andorra,AND,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,NaN,NaN,2347000.0,2949000.0,...,2189000.0,2059000.0,1830000.0,1808000.0,2242000.0,2238000.0,2328000.0,2363000.0,2663000.0,2831000.0
5,United Arab Emirates,ARE,"International tourism, number of arrivals",ST.INT.ARVL,2315000.0,2572000.0,2476000.0,2991000.0,3393000.0,3907000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Argentina,ARG,"International tourism, number of arrivals",ST.INT.ARVL,2289000.0,2614000.0,2764000.0,3012000.0,2898000.0,2909000.0,...,4562000.0,4700000.0,4308000.0,5325000.0,5705000.0,5587000.0,5246000.0,5931000.0,5736000.0,5559000.0
7,Armenia,ARM,"International tourism, number of arrivals",ST.INT.ARVL,12000.0,13000.0,23000.0,32000.0,41000.0,45000.0,...,511000.0,558000.0,575000.0,684000.0,758000.0,963000.0,1084000.0,1204000.0,1192000.0,1260000.0
8,American Samoa,ASM,"International tourism, number of arrivals",ST.INT.ARVL,34000.0,35000.0,26000.0,36000.0,41000.0,44000.0,...,24100.0,24300.0,23500.0,23100.0,22600.0,22600.0,20800.0,21600.0,20300.0,20100.0
9,Antigua and Barbuda,ATG,"International tourism, number of arrivals",ST.INT.ARVL,220000.0,228000.0,240000.0,234000.0,232000.0,207000.0,...,262000.0,266000.0,234000.0,230000.0,241000.0,247000.0,243000.0,249000.0,250000.0,265000.0
10,Australia,AUS,"International tourism, number of arrivals",ST.INT.ARVL,3726000.0,4165000.0,4318000.0,4167000.0,4459000.0,4931000.0,...,5644000.0,5586000.0,5490000.0,5790000.0,5771000.0,6032000.0,6382000.0,6884000.0,7444000.0,8263000.0
11,Austria,AUT,"International tourism, number of arrivals",ST.INT.ARVL,17173000.0,17090000.0,16647000.0,17352000.0,17467000.0,17982000.0,...,20773000.0,21935000.0,21355000.0,22004000.0,23012000.0,24151000.0,24813000.0,25291000.0,26728000.0,28121000.0
12,Azerbaijan,AZE,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,NaN,NaN,NaN,NaN,...,732000.0,1043000.0,1005000.0,1280000.0,1562000.0,1986000.0,2130000.0,2160000.0,1922000.0,2044000.0
13,Burundi,BDI,"International tourism, number of arrivals",ST.INT.ARVL,34000.0,27000.0,11000.0,15000.0,26000.0,29000.0,...,192000.0,202000.0,212000.0,142000.0,144000.0,147000.0,234000.0,235000.0,131000.0,187000.0
14,Belgium,BEL,"International tourism, number of arrivals",ST.INT.ARVL,5560000.0,5829000.0,6037000.0,6179000.0,6369000.0,6457000.0,...,7045000.0,7165000.0,6815000.0,7186000.0,7494000.0,7560000.0,7684000.0,7887000.0,8355000.0,7481000.0
15,Benin,BEN,"International tourism, number of arrivals",ST.INT.ARVL,138000.0,143000.0,148000.0,152000.0,80000.0,96000.0,...,186000.0,188000.0,190000.0,199000.0,209000.0,220000.0,231000.0,242000.0,255000.0,267000.0
16,Burkina Faso,BFA,"International tourism, number of arrivals",ST.INT.ARVL,124000.0,131000.0,138000.0,160000.0,117000.0,126000.0,...,289000.0,272000.0,269000.0,274000.0,238000.0,237000.0,218000.0,191000.0,163000.0,152000.0
17,Bangladesh,BGD,"International tourism, number of arrivals",ST.INT.ARVL,156000.0,166000.0,182000.0,172000.0,173000.0,199000.0,...,289000.0,467000.0,267000.0,303000.0,155000.0,125000.0,148000.0,125000.0,NaN,NaN
18,Bulgaria,BGR,"International tourism, number of arrivals",ST.INT.ARVL,3466000.0,2795000.0,2980000.0,2667000.0,2472000.0,2785000.0,...,5151000.0,5780000.0,5739000.0,6047000.0,6328000.0,6541000.0,6898000.0,7311000.0,7099000.0,8252000.0
19,Bahrain,BHR,"International tourism, number of arrivals",ST.INT.ARVL,2311000.0,1988000.0,2600000.0,2898000.0,3280000.0,3869000.0,...,7833000.0,8631000.0,8861000.0,11952000.0,6732000.0,8062000.0,9163000.0,10452000.0,9670000.0,10158000.0
20,"Bahamas, The",BHS,"International tourism, number of arrivals",ST.INT.ARVL,1598000.0,1633000.0,1618000.0,1528000.0,1577000.0,1544000.0,...,1528000.0,1463000.0,1327000.0,1370000.0,1346000.0,1422000.0,1366000.0,1427000.0,1484000.0,1482000.0
21,Bosnia and Herzegovina,BIH,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,115000.0,148000.0,147000.0,171000.0,...,306000.0,322000.0,311000.0,365000.0,392000.0,439000.0,529000.0,536000.0,678000.0,777000.0
22,Belarus,BLR,"International tourism, number of arrivals",ST.INT.ARVL,160600.0,234000.0,253500.0,355000.0,74900.0,60000.0,...,105000.0,90500.0,95000.0,119300.0,116000.0,6129900.0,6241800.0,5374900.0,4385600.0,9423500.0
23,Belize,BLZ,"International tourism, number of arrivals",ST.INT.ARVL,131000.0,133000.0,146000.0,176000.0,181000.0,196000.0,...,251000.0,245000.0,232000.0,242000.0,250000.0,277000.0,294000.0,321000.0,341000.0,386000.0
24,Bermuda,BMU,"International tourism, number of arrivals",ST.INT.ARVL,387000.0,390000.0,380000.0,370000.0,355000.0,332000.0,...,306000.0,264000.0,236000.0,232000.0,236000.0,232000.0,236000.0,224000.0,220000.0,244000.0
25,Bolivia,BOL,"International tourism, number of arrivals",ST.INT.ARVL,284000.0,313000.0,355000.0,387000.0,342000.0,319000.0,...,573000.0,594000.0,599000.0,679000.0,711000.0,798000.0,798000.0,871000.0,882000.0,959000.0
26,Brazil,BRA,"International tourism, number of arrivals",ST.INT.ARVL,1991000.0,2666000.0,2850000.0,4818000.0,5107000.0,5313000.0,...,5026000.0,5050000.0,4802000.0,5161000.0,5433000.0,5677000.0,5813000.0,6430000.0,6306000.0,6578000.0
27,Barbados,BRB,"International tourism, number of arrivals",ST.INT.ARVL,442000.0,447000.0,472000.0,512000.0,515000.0,545000.0,...,575000.0,568000.0,519000.0,532000.0,568000.0,536000.0,509000.0,521000.0,592000.0,632000.0
28,Brunei Darussalam,BRN,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,NaN,NaN,NaN,NaN,...,179000.0,226000.0,157000.0,214000.0,242000.0,209000.0,225000.0,201000.0,218000.0,219000.0
29,Bhutan,BTN,"International tourism, number of arrivals",ST.INT.ARVL,4800.0,5200.0,5400.0,6200.0,7200.0,7600.0,...,21000.0,28000.0,23000.0,41000.0,66000.0,105000.0,116000.0,133000.0,155000.0,210000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Turks and Caicos Islands,TCA,"International tourism, number of arrivals",ST.INT.ARVL,79000.0,88000.0,93000.0,111000.0,121000.0,152000.0,...,265000.0,352000.0,351000.0,281000.0,354000.0,291700.0,290600.0,357000.0,386000.0,454000.0
191,Chad,TCD,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,NaN,NaN,NaN,NaN,...,77000.0,60600.0,70000.0,71000.0,77000.0,86000.0,100000.0,122000.0,119800.0,NaN
192,Togo,TGO,"International tourism, number of arrivals",ST.INT.ARVL,53000.0,58000.0,92000.0,69000.0,70000.0,60000.0,...,86000.0,74000.0,150000.0,202000.0,300000.0,235000.0,327000.0,282000.0,273000.0,338000.0
193,Thailand,THA,"International tourism, number of arrivals",ST.INT.ARVL,6952000.0,7244000.0,7294000.0,7843000.0,8651000.0,9579000.0,...,14464000.0,14584000.0,14150000.0,15936000.0,19230000.0,22354000.0,26547000.0,24810000.0,29923000.0,32530000.0
194,Tajikistan,TJK,"International tourism, number of arrivals",ST.INT.ARVL,NaN,700.0,2100.0,3200.0,4500.0,7700.0,...,NaN,325000.0,207000.0,160000.0,183000.0,244000.0,208000.0,213000.0,414000.0,NaN
195,Turkmenistan,TKM,"International tourism, number of arrivals",ST.INT.ARVL,218000.0,217000.0,257000.0,300000.0,NaN,3400.0,...,8200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,Timor-Leste,TLS,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,NaN,NaN,NaN,NaN,...,22000.0,36000.0,44000.0,40000.0,51000.0,58000.0,79000.0,60000.0,62000.0,66000.0
197,Tonga,TON,"International tourism, number of arrivals",ST.INT.ARVL,29000.0,27000.0,26000.0,27000.0,31000.0,35000.0,...,46000.0,50000.0,45700.0,47100.0,46000.0,47400.0,48200.0,50400.0,53800.0,59100.0
198,Trinidad and Tobago,TTO,"International tourism, number of arrivals",ST.INT.ARVL,260000.0,266000.0,324000.0,334000.0,358000.0,399000.0,...,449000.0,437000.0,419000.0,388000.0,431000.0,455000.0,434000.0,412000.0,440000.0,410000.0
199,Tunisia,TUN,"International tourism, number of arrivals",ST.INT.ARVL,4120000.0,3885000.0,4263000.0,4718000.0,4832000.0,5058000.0,...,6762000.0,7050000.0,7797000.0,7828000.0,5746000.0,6999000.0,7352000.0,7163000.0,5359000.0,5724000.0
200,Turkey,TUR,"International tourism, number of arrivals",ST.INT.ARVL,7083000.0,7966000.0,9040000.0,8960000.0,6893000.0,9586000.0,...,26122000.0,29792000.0,30187000.0,31364000.0,34654000.0,35698000.0,37795000.0,39811000.0,39478000.0,30289000.0
201,Tuvalu,TUV,"International tourism, number of arrivals",ST.INT.ARVL,900.0,1000.0,1000.0,1000.0,1100.0,1100.0,...,1100.0,1700.0,1600.0,1700.0,1200.0,1100.0,1300.0,1400.0,2400.0,2500.0
202,Tanzania,TZA,"International tourism, number of arrivals",ST.INT.ARVL,285000.0,315000.0,347000.0,450000.0,564000.0,459000.0,...,692000.0,750000.0,695000.0,754000.0,843000.0,1043000.0,1063000.0,1113000.0,1104000.0,1233000.0
203,Uganda,UGA,"International tourism, number of arrivals",ST.INT.ARVL,160000.0,174000.0,175000.0,195000.0,189000.0,193000.0,...,642000.0,844000.0,807000.0,946000.0,1151000.0,1197000.0,1206000.0,1266000.0,1303000.0,1323000.0
204,Ukraine,UKR,"International tourism, number of arrivals",ST.INT.ARVL,3716000.0,3854000.0,7558000.0,6208000.0,4232000.0,6431000.0,...,23122000.0,25449000.0,20798000.0,21203000.0,21415000.0,23013000.0,24671000.0,12712000.0,12428000.0,13333000.0
205,Uruguay,URY,"International tourism, number of arrivals",ST.INT.ARVL,2022000.0,2152000.0,2316000.0,2163000.0,2073000.0,1968000.0,...,1753000.0,1938000.0,2055000.0,2353000.0,2857000.0,2695000.0,2683000.0,2682000.0,2773000.0,3037000.0
206,United States,USA,"International tourism, number of arrivals",ST.INT.ARVL,43318000.0,46489000.0,47767000.0,46377000.0,48509000.0,51238000.0,...,56135000.0,58007000.0,55103000.0,60010000.0,62821000.0,66657000.0,69995000.0,75022000.0,77465000.0,75608000.0
207,Uzbekistan,UZB,"International tourism, number of arrivals",ST.INT.ARVL,92000.0,173000.0,960000.0,811000.0,487000.0,302000.0,...,903000.0,1069000.0,1215000.0,975000.0,NaN,NaN,1969000.0,NaN,NaN,NaN
208,St. Vincent and the Grenadines,VCT,"International tourism, number of arrivals",ST.INT.ARVL,60000.0,58000.0,65000.0,67000.0,68000.0,73000.0,...,90000.0,84000.0,75000.0,72000.0,74000.0,74000.0,72000.0,71000.0,75000.0,79000.0
209,"Venezuela, RB",VEN,"International tourism, number of arrivals",ST.INT.ARVL,700000.0,759000.0,814000.0,685000.0,587000.0,469000.0,...,756000.0,699000.0,562000.0,526000.0,595000.0,988000.0,986000.0,857000.0,789000.0,601000.0
210,British Virgin Islands,VGB,"International tourism, number of arrivals",ST.INT.ARVL,219000.0,244000.0,244000.0,279000.0,284000.0,272000.0,...,358000.0,346000.0,309000.0,330000.0,338000.0,351000.0,366000.0,386000.0,393000.0,408000.0
211,Virgin Islands (U.S.),VIR,"International tourism, number of arrivals",ST.INT.ARVL,454000.0,373000.0,393000.0,422000.0,484000.0,546000.0,...,587000.0,574000.0,563000.0,572000.0,567000.0,620000.0,590000.0,615000.0,642000.0,NaN
212,Vietnam,VNM,"International tourism, number of arrivals",ST.INT.ARVL,1351000.0,1607000.0,1716000.0,1520000.0,1782000.0,2140000.0,...,4229000.0,4236000.0,3747000.0,5050000.0,6014000.0,6848000.0,7572000.0,7874000.0,7944000.0,10013000.0
213,Vanuatu,VUT,"International tourism, number of arrivals",ST.INT.ARVL,44000.0,46000.0,50000.0,52000.0,51000.0,58000.0,...,81000.0,90500.0,100700.0,97200.0,94000.0,108200.0,110000.0,109000.0,90000.0,95100.0
214,Samoa,WSM,"International tourism, number of arrivals",ST.INT.ARVL,68000.0,73000.0,68000.0,78000.0,85000.0,88000.0,...,117000.0,118000.0,122000.0,122000.0,121000.0,126000.0,116000.0,120400.0,128000.0,134000.0
215,Kosovo,XKX,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
216,"Yemen, Rep.",YEM,"International tourism, number of arrivals",ST.INT.ARVL,61000.0,74000.0,80000.0,88000.0,58000.0,73000.0,...,948000.0,1023000.0,1028000.0,1025000.0,829000.0,874000.0,990000.0,1017500.0,366700.0,NaN
217,South Africa,ZAF,"International tourism, number of arrivals",ST.INT.ARVL,4488000.0,4915000.0,4976000.0,5732000.0,5890000.0,5872000.0,...,9091000.0,9592000.0,7012000.0,8074000.0,8339000.0,9188000.0,9537000.0,9549000.0,8904000.0,10044000.0
218,Zambia,ZMB,"International tourism, number of arrivals",ST.INT.ARVL,163000.0,264000.0,341000.0,362000.0,404000.0,457000.0,...,897000.0,812000.0,710000.0,815000.0,920000.0,859000.0,915000.0,947000.0,932000.0,956000.0
219,Zimbabwe,ZWE,"International tourism, number of arrivals",ST.INT.ARVL,1416000.0,1597000.0,1336000.0,2090000.0,2250000.0,1967000.0,...,2506000.0,1956000.0,2017000.0,2239000.0,2423000.0,1794000.0,1833000.0,1880000.0,2057000.0,2168000.0

We won't need the Indicator_Name and Ind_Code columns. So remove 'em.
Let's set the Country_Name as the index and then sort in ascending order.
Check the order by viewing only the Country_Name column.

In [7]:
import pandas as pd
import numpy as np
df2 = dataFile.drop(['Indicator_Name','Ind_Code'], axis=1)
df2 = df2.set_index('Country_Name')
df2.sort_index(inplace=True)
df2

,Code,1995,1996,1997,1998,1999,2000,2001,2002,2003,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
Country_Name,,,,,,,,,,,,,,,,,,,,,
Afghanistan,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Albania,ALB,304000.0,287000.0,119000.0,184000.0,371000.0,317000.0,354000.0,470000.0,557000.0,...,1062000.0,1247000.0,1711000.0,2191000.0,2469000.0,3156000.0,2857000.0,3341000.0,3784000.0,4070000.0
Algeria,DZA,520000.0,605000.0,635000.0,678000.0,749000.0,866000.0,901000.0,988000.0,1166000.0,...,1743000.0,1772000.0,1912000.0,2070000.0,2395000.0,2634000.0,2733000.0,2301000.0,1710000.0,2039000.0
American Samoa,ASM,34000.0,35000.0,26000.0,36000.0,41000.0,44000.0,36000.0,NaN,NaN,...,24100.0,24300.0,23500.0,23100.0,22600.0,22600.0,20800.0,21600.0,20300.0,20100.0
Andorra,AND,NaN,NaN,NaN,NaN,2347000.0,2949000.0,3516000.0,3387000.0,3138000.0,...,2189000.0,2059000.0,1830000.0,1808000.0,2242000.0,2238000.0,2328000.0,2363000.0,2663000.0,2831000.0
Angola,AGO,9000.0,21000.0,45000.0,52000.0,45000.0,51000.0,67000.0,91000.0,107000.0,...,195000.0,294000.0,366000.0,425000.0,481000.0,528000.0,650000.0,595000.0,592000.0,397000.0
Antigua and Barbuda,ATG,220000.0,228000.0,240000.0,234000.0,232000.0,207000.0,215000.0,218000.0,239000.0,...,262000.0,266000.0,234000.0,230000.0,241000.0,247000.0,243000.0,249000.0,250000.0,265000.0
Argentina,ARG,2289000.0,2614000.0,2764000.0,3012000.0,2898000.0,2909000.0,2620000.0,2820000.0,2995000.0,...,4562000.0,4700000.0,4308000.0,5325000.0,5705000.0,5587000.0,5246000.0,5931000.0,5736000.0,5559000.0
Armenia,ARM,12000.0,13000.0,23000.0,32000.0,41000.0,45000.0,123000.0,162000.0,206000.0,...,511000.0,558000.0,575000.0,684000.0,758000.0,963000.0,1084000.0,1204000.0,1192000.0,1260000.0
Aruba,ABW,619000.0,641000.0,650000.0,647000.0,683000.0,721000.0,691000.0,643000.0,642000.0,...,772000.0,827000.0,813000.0,824000.0,869000.0,904000.0,979000.0,1072000.0,1225000.0,1102000.0
Australia,AUS,3726000.0,4165000.0,4318000.0,4167000.0,4459000.0,4931000.0,4856000.0,4841000.0,4746000.0,...,5644000.0,5586000.0,5490000.0,5790000.0,5771000.0,6032000.0,6382000.0,6884000.0,7444000.0,8263000.0
Austria,AUT,17173000.0,17090000.0,16647000.0,17352000.0,17467000.0,17982000.0,18180000.0,18611000.0,19078000.0,...,20773000.0,21935000.0,21355000.0,22004000.0,23012000.0,24151000.0,24813000.0,25291000.0,26728000.0,28121000.0
Azerbaijan,AZE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,576000.0,768000.0,...,732000.0,1043000.0,1005000.0,1280000.0,1562000.0,1986000.0,2130000.0,2160000.0,1922000.0,2044000.0
"Bahamas, The",BHS,1598000.0,1633000.0,1618000.0,1528000.0,1577000.0,1544000.0,1538000.0,1513000.0,1510000.0,...,1528000.0,1463000.0,1327000.0,1370000.0,1346000.0,1422000.0,1366000.0,1427000.0,1484000.0,1482000.0
Bahrain,BHR,2311000.0,1988000.0,2600000.0,2898000.0,3280000.0,3869000.0,4388000.0,4831000.0,4844000.0,...,7833000.0,8631000.0,8861000.0,11952000.0,6732000.0,8062000.0,9163000.0,10452000.0,9670000.0,10158000.0
Bangladesh,BGD,156000.0,166000.0,182000.0,172000.0,173000.0,199000.0,207000.0,207000.0,245000.0,...,289000.0,467000.0,267000.0,303000.0,155000.0,125000.0,148000.0,125000.0,NaN,NaN
Barbados,BRB,442000.0,447000.0,472000.0,512000.0,515000.0,545000.0,507000.0,498000.0,531000.0,...,575000.0,568000.0,519000.0,532000.0,568000.0,536000.0,509000.0,521000.0,592000.0,632000.0
Belarus,BLR,160600.0,234000.0,253500.0,355000.0,74900.0,60000.0,61000.0,63000.0,64000.0,...,105000.0,90500.0,95000.0,119300.0,116000.0,6129900.0,6241800.0,5374900.0,4385600.0,9423500.0
Belgium,BEL,5560000.0,5829000.0,6037000.0,6179000.0,6369000.0,6457000.0,6452000.0,6720000.0,6690000.0,...,7045000.0,7165000.0,6815000.0,7186000.0,7494000.0,7560000.0,7684000.0,7887000.0,8355000.0,7481000.0
Belize,BLZ,131000.0,133000.0,146000.0,176000.0,181000.0,196000.0,196000.0,200000.0,221000.0,...,251000.0,245000.0,232000.0,242000.0,250000.0,277000.0,294000.0,321000.0,341000.0,386000.0
Benin,BEN,138000.0,143000.0,148000.0,152000.0,80000.0,96000.0,88000.0,72000.0,175000.0,...,186000.0,188000.0,190000.0,199000.0,209000.0,220000.0,231000.0,242000.0,255000.0,267000.0
Bermuda,BMU,387000.0,390000.0,380000.0,370000.0,355000.0,332000.0,278000.0,284000.0,257000.0,...,306000.0,264000.0,236000.0,232000.0,236000.0,232000.0,236000.0,224000.0,220000.0,244000.0
Bhutan,BTN,4800.0,5200.0,5400.0,6200.0,7200.0,7600.0,6400.0,5600.0,6300.0,...,21000.0,28000.0,23000.0,41000.0,66000.0,105000.0,116000.0,133000.0,155000.0,210000.0
Bolivia,BOL,284000.0,313000.0,355000.0,387000.0,342000.0,319000.0,316000.0,334000.0,427000.0,...,573000.0,594000.0,599000.0,679000.0,711000.0,798000.0,798000.0,871000.0,882000.0,959000.0
Bosnia and Herzegovina,BIH,NaN,NaN,115000.0,148000.0,147000.0,171000.0,139000.0,160000.0,165000.0,...,306000.0,322000.0,311000.0,365000.0,392000.0,439000.0,529000.0,536000.0,678000.0,777000.0
Botswana,BWA,521000.0,512000.0,607000.0,750000.0,843000.0,1104000.0,1193000.0,1274000.0,1406000.0,...,1736000.0,2101000.0,1721000.0,1973000.0,NaN,1614000.0,1544000.0,1966000.0,1528000.0,NaN
Brazil,BRA,1991000.0,2666000.0,2850000.0,4818000.0,5107000.0,5313000.0,4773000.0,3785000.0,4133000.0,...,5026000.0,5050000.0,4802000.0,5161000.0,5433000.0,5677000.0,5813000.0,6430000.0,6306000.0,6578000.0
British Virgin Islands,VGB,219000.0,244000.0,244000.0,279000.0,284000.0,272000.0,296000.0,282000.0,278000.0,...,358000.0,346000.0,309000.0,330000.0,338000.0,351000.0,366000.0,386000.0,393000.0,408000.0
Brunei Darussalam,BRN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,179000.0,226000.0,157000.0,214000.0,242000.0,209000.0,225000.0,201000.0,218000.0,219000.0
Bulgaria,BGR,3466000.0,2795000.0,2980000.0,2667000.0,2472000.0,2785000.0,3186000.0,3433000.0,4048000.0,...,5151000.0,5780000.0,5739000.0,6047000.0,6328000.0,6541000.0,6898000.0,7311000.0,7099000.0,8252000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sweden,SWE,2310000.0,2376000.0,2388000.0,2573000.0,2595000.0,3828000.0,4108000.0,4276000.0,4268000.0,...,5224000.0,4555000.0,4899000.0,5183000.0,5222000.0,5146000.0,5229000.0,5660000.0,6482000.0,6782000.0
Switzerland,CHE,6946000.0,6730000.0,7039000.0,7185000.0,7154000.0,7821000.0,7455000.0,6868000.0,6530000.0,...,8448000.0,8608000.0,8294000.0,8628000.0,8534000.0,8566000.0,8967000.0,9158000.0,9305000.0,9205000.0
Syrian Arab Republic,SYR,815000.0,830000.0,891000.0,1267000.0,1386000.0,2100000.0,2192000.0,2661000.0,2598000.0,...,4158000.0,5430000.0,6092000.0,8546000.0,5070000.0,NaN,NaN,NaN,NaN,NaN
Tajikistan,TJK,NaN,700.0,2100.0,3200.0,4500.0,7700.0,5200.0,NaN,NaN,...,NaN,325000.0,207000.0,160000.0,183000.0,244000.0,208000.0,213000.0,414000.0,NaN
Tanzania,TZA,285000.0,315000.0,347000.0,450000.0,564000.0,459000.0,501000.0,550000.0,552000.0,...,692000.0,750000.0,695000.0,754000.0,843000.0,1043000.0,1063000.0,1113000.0,1104000.0,1233000.0
Thailand,THA,6952000.0,7244000.0,7294000.0,7843000.0,8651000.0,9579000.0,10133000.0,10873000.0,10082000.0,...,14464000.0,14584000.0,14150000.0,15936000.0,19230000.0,22354000.0,26547000.0,24810000.0,29923000.0,32530000.0
Timor-Leste,TLS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22000.0,36000.0,44000.0,40000.0,51000.0,58000.0,79000.0,60000.0,62000.0,66000.0
Togo,TGO,53000.0,58000.0,92000.0,69000.0,70000.0,60000.0,57000.0,58000.0,61000.0,...,86000.0,74000.0,150000.0,202000.0,300000.0,235000.0,327000.0,282000.0,273000.0,338000.0
Tonga,TON,29000.0,27000.0,26000.0,27000.0,31000.0,35000.0,32000.0,37000.0,40000.0,...,46000.0,50000.0,45700.0,47100.0,46000.0,47400.0,48200.0,50400.0,53800.0,59100.0
Trinidad and Tobago,TTO,260000.0,266000.0,324000.0,334000.0,358000.0,399000.0,383000.0,384000.0,409000.0,...,449000.0,437000.0,419000.0,388000.0,431000.0,455000.0,434000.0,412000.0,440000.0,410000.0
Tunisia,TUN,4120000.0,3885000.0,4263000.0,4718000.0,4832000.0,5058000.0,5387000.0,5064000.0,5114000.0,...,6762000.0,7050000.0,7797000.0,7828000.0,5746000.0,6999000.0,7352000.0,7163000.0,5359000.0,5724000.0
Turkey,TUR,7083000.0,7966000.0,9040000.0,8960000.0,6893000.0,9586000.0,10783000.0,12790000.0,13341000.0,...,26122000.0,29792000.0,30187000.0,31364000.0,34654000.0,35698000.0,37795000.0,39811000.0,39478000.0,30289000.0
Turkmenistan,TKM,218000.0,217000.0,257000.0,300000.0,NaN,3400.0,5200.0,10800.0,8200.0,...,8200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Turks and Caicos Islands,TCA,79000.0,88000.0,93000.0,111000.0,121000.0,152000.0,166000.0,155000.0,164000.0,...,265000.0,352000.0,351000.0,281000.0,354000.0,291700.0,290600.0,357000.0,386000.0,454000.0
Tuvalu,TUV,900.0,1000.0,1000.0,1000.0,1100.0,1100.0,1100.0,1300.0,1400.0,...,1100.0,1700.0,1600.0,1700.0,1200.0,1100.0,1300.0,1400.0,2400.0,2500.0
Uganda,UGA,160000.0,174000.0,175000.0,195000.0,189000.0,193000.0,205000.0,254000.0,305000.0,...,642000.0,844000.0,807000.0,946000.0,1151000.0,1197000.0,1206000.0,1266000.0,1303000.0,1323000.0
Ukraine,UKR,3716000.0,3854000.0,7558000.0,6208000.0,4232000.0,6431000.0,9174000.0,10517000.0,12514000.0,...,23122000.0,25449000.0,20798000.0,21203000.0,21415000.0,23013000.0,24671000.0,12712000.0,12428000.0,13333000.0
United Arab Emirates,ARE,2315000.0,2572000.0,2476000.0,2991000.0,3393000.0,3907000.0,4134000.0,5445000.0,5871000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United Kingdom,GBR,21719000.0,22936000.0,23215000.0,23710000.0,23341000.0,23212000.0,20982000.0,22307000.0,22787000.0,...,30870000.0,30142000.0,28199000.0,28295000.0,29306000.0,29282000.0,31063000.0,32613000.0,34436000.0,35814000.0
United States,USA,43318000.0,46489000.0,47767000.0,46377000.0,48509000.0,51238000.0,46927000.0,43581000.0,41218000.0,...,56135000.0,58007000.0,55103000.0,60010000.0,62821000.0,66657000.0,69995000.0,75022000.0,77465000.0,75608000.0
Uruguay,URY,2022000.0,2152000.0,2316000.0,2163000.0,2073000.0,1968000.0,1892000.0,1258000.0,1420000.0,...,1753000.0,1938000.0,2055000.0,2353000.0,2857000.0,2695000.0,2683000.0,2682000.0,2773000.0,3037000.0
Uzbekistan,UZB,92000.0,173000.0,960000.0,811000.0,487000.0,302000.0,345000.0,332000.0,231000.0,...,903000.0,1069000.0,1215000.0,975000.0,NaN,NaN,1969000.0,NaN,NaN,NaN
Vanuatu,VUT,44000.0,46000.0,50000.0,52000.0,51000.0,58000.0,53000.0,49000.0,50000.0,...,81000.0,90500.0,100700.0,97200.0,94000.0,108200.0,110000.0,109000.0,90000.0,95100.0
"Venezuela, RB",VEN,700000.0,759000.0,814000.0,685000.0,587000.0,469000.0,584000.0,432000.0,337000.0,...,756000.0,699000.0,562000.0,526000.0,595000.0,988000.0,986000.0,857000.0,789000.0,601000.0
Vietnam,VNM,1351000.0,1607000.0,1716000.0,1520000.0,1782000.0,2140000.0,2330000.0,2628000.0,2429000.0,...,4229000.0,4236000.0,3747000.0,5050000.0,6014000.0,6848000.0,7572000.0,7874000.0,7944000.0,10013000.0
Virgin Islands (U.S.),VIR,454000.0,373000.0,393000.0,422000.0,484000.0,546000.0,527000.0,520000.0,538000.0,...,587000.0,574000.0,563000.0,572000.0,567000.0,620000.0,590000.0,615000.0,642000.0,NaN
West Bank and Gaza,PSE,NaN,220000.0,210000.0,200000.0,300000.0,310000.0,43000.0,33000.0,37000.0,...,264000.0,387000.0,396000.0,522000.0,449000.0,490000.0,545000.0,556000.0,432000.0,400000.0
"Yemen, Rep.",YEM,61000.0,74000.0,80000.0,88000.0,58000.0,73000.0,76000.0,98000.0,155000.0,...,948000.0,1023000.0,1028000.0,1025000.0,829000.0,874000.0,990000.0,1017500.0,366700.0,NaN
Zambia,ZMB,163000.0,264000.0,341000.0,362000.0,404000.0,457000.0,492000.0,565000.0,413000.0,...,897000.0,812000.0,710000.0,815000.0,920000.0,859000.0,915000.0,947000.0,932000.0,956000.0
Zimbabwe,ZWE,1416000.0,1597000.0,1336000.0,2090000.0,2250000.0,1967000.0,2217000.0,2041000.0,2256000.0,...,2506000.0,1956000.0,2017000.0,2239000.0,2423000.0,1794000.0,1833000.0,1880000.0,2057000.0,2168000.0

Even if not entirely applicable yet, what are quartiles, count, min and max, etc., of these data?

In [8]:
df2.describe()

,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
count,1.840000e+02,1.880000e+02,1.890000e+02,1.910000e+02,1.910000e+02,1.950000e+02,1.950000e+02,1.930000e+02,1.940000e+02,1.950000e+02,...,2.010000e+02,2.020000e+02,2.000000e+02,2.010000e+02,1.990000e+02,1.980000e+02,1.970000e+02,1.920000e+02,1.920000e+02,1.770000e+02
mean,4.165775e+06,4.267208e+06,4.486755e+06,4.637892e+06,4.850701e+06,5.126317e+06,5.098171e+06,5.270684e+06,5.171912e+06,5.521902e+06,...,6.354392e+06,6.395879e+06,6.174724e+06,6.495266e+06,6.850012e+06,7.197645e+06,7.577733e+06,8.155017e+06,8.491314e+06,9.479874e+06
std,1.654926e+07,1.695803e+07,1.806205e+07,1.879735e+07,1.971219e+07,2.065817e+07,2.040447e+07,2.088075e+07,2.059272e+07,2.090504e+07,...,2.338472e+07,2.315295e+07,2.220427e+07,2.279790e+07,2.421599e+07,2.487328e+07,2.597656e+07,2.747352e+07,2.865148e+07,3.068391e+07
min,9.000000e+02,7.000000e+02,1.000000e+03,1.000000e+03,1.100000e+03,1.100000e+03,1.100000e+03,1.300000e+03,1.400000e+03,1.300000e+03,...,1.100000e+03,1.700000e+03,1.600000e+03,1.700000e+03,1.200000e+03,1.100000e+03,1.300000e+03,1.400000e+03,2.400000e+03,2.500000e+03
25%,1.075000e+05,1.055000e+05,1.150000e+05,1.375000e+05,1.190000e+05,1.205000e+05,1.250000e+05,1.400000e+05,1.632500e+05,1.860000e+05,...,2.620000e+05,2.645000e+05,2.635000e+05,2.520000e+05,2.595000e+05,2.896750e+05,3.190000e+05,3.357500e+05,3.657750e+05,4.000000e+05
50%,3.950000e+05,3.730000e+05,3.950000e+05,4.500000e+05,4.870000e+05,4.840000e+05,5.070000e+05,5.500000e+05,5.650000e+05,6.410000e+05,...,8.970000e+05,9.035000e+05,9.740000e+05,9.750000e+05,1.018000e+06,1.095000e+06,1.274000e+06,1.344000e+06,1.425000e+06,1.889000e+06
75%,2.233500e+06,2.186000e+06,2.374000e+06,2.466000e+06,2.538500e+06,2.963500e+06,3.071500e+06,3.111000e+06,3.237750e+06,3.457000e+06,...,4.158000e+06,4.082750e+06,3.839750e+06,4.207000e+06,5.016500e+06,5.000250e+06,5.246000e+06,5.727750e+06,5.777250e+06,6.782000e+06
max,1.968470e+08,2.024660e+08,2.176270e+08,2.295580e+08,2.409920e+08,2.552200e+08,2.534570e+08,2.590720e+08,2.579980e+08,2.597160e+08,...,2.932260e+08,2.903240e+08,2.772700e+08,2.838790e+08,3.010300e+08,3.075760e+08,3.211940e+08,3.358660e+08,3.511690e+08,3.646550e+08

Exponential notation is fine but for our purposes, let's pretty up the data by formatting them with commas and round off to 0 decimal places.

In [9]:
pd.options.display.float_format = '{:,.0f}'.format
df2

,Code,1995,1996,1997,1998,1999,2000,2001,2002,2003,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
Country_Name,,,,,,,,,,,,,,,,,,,,,
Afghanistan,AFG,nan,nan,nan,nan,nan,nan,nan,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
Albania,ALB,"304,000","287,000","119,000","184,000","371,000","317,000","354,000","470,000","557,000",...,"1,062,000","1,247,000","1,711,000","2,191,000","2,469,000","3,156,000","2,857,000","3,341,000","3,784,000","4,070,000"
Algeria,DZA,"520,000","605,000","635,000","678,000","749,000","866,000","901,000","988,000","1,166,000",...,"1,743,000","1,772,000","1,912,000","2,070,000","2,395,000","2,634,000","2,733,000","2,301,000","1,710,000","2,039,000"
American Samoa,ASM,"34,000","35,000","26,000","36,000","41,000","44,000","36,000",nan,nan,...,"24,100","24,300","23,500","23,100","22,600","22,600","20,800","21,600","20,300","20,100"
Andorra,AND,nan,nan,nan,nan,"2,347,000","2,949,000","3,516,000","3,387,000","3,138,000",...,"2,189,000","2,059,000","1,830,000","1,808,000","2,242,000","2,238,000","2,328,000","2,363,000","2,663,000","2,831,000"
Angola,AGO,"9,000","21,000","45,000","52,000","45,000","51,000","67,000","91,000","107,000",...,"195,000","294,000","366,000","425,000","481,000","528,000","650,000","595,000","592,000","397,000"
Antigua and Barbuda,ATG,"220,000","228,000","240,000","234,000","232,000","207,000","215,000","218,000","239,000",...,"262,000","266,000","234,000","230,000","241,000","247,000","243,000","249,000","250,000","265,000"
Argentina,ARG,"2,289,000","2,614,000","2,764,000","3,012,000","2,898,000","2,909,000","2,620,000","2,820,000","2,995,000",...,"4,562,000","4,700,000","4,308,000","5,325,000","5,705,000","5,587,000","5,246,000","5,931,000","5,736,000","5,559,000"
Armenia,ARM,"12,000","13,000","23,000","32,000","41,000","45,000","123,000","162,000","206,000",...,"511,000","558,000","575,000","684,000","758,000","963,000","1,084,000","1,204,000","1,192,000","1,260,000"
Aruba,ABW,"619,000","641,000","650,000","647,000","683,000","721,000","691,000","643,000","642,000",...,"772,000","827,000","813,000","824,000","869,000","904,000","979,000","1,072,000","1,225,000","1,102,000"
Australia,AUS,"3,726,000","4,165,000","4,318,000","4,167,000","4,459,000","4,931,000","4,856,000","4,841,000","4,746,000",...,"5,644,000","5,586,000","5,490,000","5,790,000","5,771,000","6,032,000","6,382,000","6,884,000","7,444,000","8,263,000"
Austria,AUT,"17,173,000","17,090,000","16,647,000","17,352,000","17,467,000","17,982,000","18,180,000","18,611,000","19,078,000",...,"20,773,000","21,935,000","21,355,000","22,004,000","23,012,000","24,151,000","24,813,000","25,291,000","26,728,000","28,121,000"
Azerbaijan,AZE,nan,nan,nan,nan,nan,nan,nan,"576,000","768,000",...,"732,000","1,043,000","1,005,000","1,280,000","1,562,000","1,986,000","2,130,000","2,160,000","1,922,000","2,044,000"
"Bahamas, The",BHS,"1,598,000","1,633,000","1,618,000","1,528,000","1,577,000","1,544,000","1,538,000","1,513,000","1,510,000",...,"1,528,000","1,463,000","1,327,000","1,370,000","1,346,000","1,422,000","1,366,000","1,427,000","1,484,000","1,482,000"
Bahrain,BHR,"2,311,000","1,988,000","2,600,000","2,898,000","3,280,000","3,869,000","4,388,000","4,831,000","4,844,000",...,"7,833,000","8,631,000","8,861,000","11,952,000","6,732,000","8,062,000","9,163,000","10,452,000","9,670,000","10,158,000"
Bangladesh,BGD,"156,000","166,000","182,000","172,000","173,000","199,000","207,000","207,000","245,000",...,"289,000","467,000","267,000","303,000","155,000","125,000","148,000","125,000",nan,nan
Barbados,BRB,"442,000","447,000","472,000","512,000","515,000","545,000","507,000","498,000","531,000",...,"575,000","568,000","519,000","532,000","568,000","536,000","509,000","521,000","592,000","632,000"
Belarus,BLR,"160,600","234,000","253,500","355,000","74,900","60,000","61,000","63,000","64,000",...,"105,000","90,500","95,000","119,300","116,000","6,129,900","6,241,800","5,374,900","4,385,600","9,423,500"
Belgium,BEL,"5,560,000","5,829,000","6,037,000","6,179,000","6,369,000","6,457,000","6,452,000","6,720,000","6,690,000",...,"7,045,000","7,165,000","6,815,000","7,186,000","7,494,000","7,560,000","7,684,000","7,887,000","8,355,000","7,481,000"
Belize,BLZ,"131,000","133,000","146,000","176,000","181,000","196,000","196,000","200,000","221,000",...,"251,000","245,000","232,000","242,000","250,000","277,000","294,000","321,000","341,000","386,000"
Benin,BEN,"138,000","143,000","148,000","152,000","80,000","96,000","88,000","72,000","175,000",...,"186,000","188,000","190,000","199,000","209,000","220,000","231,000","242,000","255,000","267,000"
Bermuda,BMU,"387,000","390,000","380,000","370,000","355,000","332,000","278,000","284,000","257,000",...,"306,000","264,000","236,000","232,000","236,000","232,000","236,000","224,000","220,000","244,000"
Bhutan,BTN,"4,800","5,200","5,400","6,200","7,200","7,600","6,400","5,600","6,300",...,"21,000","28,000","23,000","41,000","66,000","105,000","116,000","133,000","155,000","210,000"
Bolivia,BOL,"284,000","313,000","355,000","387,000","342,000","319,000","316,000","334,000","427,000",...,"573,000","594,000","599,000","679,000","711,000","798,000","798,000","871,000","882,000","959,000"
Bosnia and Herzegovina,BIH,nan,nan,"115,000","148,000","147,000","171,000","139,000","160,000","165,000",...,"306,000","322,000","311,000","365,000","392,000","439,000","529,000","536,000","678,000","777,000"
Botswana,BWA,"521,000","512,000","607,000","750,000","843,000","1,104,000","1,193,000","1,274,000","1,406,000",...,"1,736,000","2,101,000","1,721,000","1,973,000",nan,"1,614,000","1,544,000","1,966,000","1,528,000",nan
Brazil,BRA,"1,991,000","2,666,000","2,850,000","4,818,000","5,107,000","5,313,000","4,773,000","3,785,000","4,133,000",...,"5,026,000","5,050,000","4,802,000","5,161,000","5,433,000","5,677,000","5,813,000","6,430,000","6,306,000","6,578,000"
British Virgin Islands,VGB,"219,000","244,000","244,000","279,000","284,000","272,000","296,000","282,000","278,000",...,"358,000","346,000","309,000","330,000","338,000","351,000","366,000","386,000","393,000","408,000"
Brunei Darussalam,BRN,nan,nan,nan,nan,nan,nan,nan,nan,nan,...,"179,000","226,000","157,000","214,000","242,000","209,000","225,000","201,000","218,000","219,000"
Bulgaria,BGR,"3,466,000","2,795,000","2,980,000","2,667,000","2,472,000","2,785,000","3,186,000","3,433,000","4,048,000",...,"5,151,000","5,780,000","5,739,000","6,047,000","6,328,000","6,541,000","6,898,000","7,311,000","7,099,000","8,252,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sweden,SWE,"2,310,000","2,376,000","2,388,000","2,573,000","2,595,000","3,828,000","4,108,000","4,276,000","4,268,000",...,"5,224,000","4,555,000","4,899,000","5,183,000","5,222,000","5,146,000","5,229,000","5,660,000","6,482,000","6,782,000"
Switzerland,CHE,"6,946,000","6,730,000","7,039,000","7,185,000","7,154,000","7,821,000","7,455,000","6,868,000","6,530,000",...,"8,448,000","8,608,000","8,294,000","8,628,000","8,534,000","8,566,000","8,967,000","9,158,000","9,305,000","9,205,000"
Syrian Arab Republic,SYR,"815,000","830,000","891,000","1,267,000","1,386,000","2,100,000","2,192,000","2,661,000","2,598,000",...,"4,158,000","5,430,000","6,092,000","8,546,000","5,070,000",nan,nan,nan,nan,nan
Tajikistan,TJK,nan,700,"2,100","3,200","4,500","7,700","5,200",nan,nan,...,nan,"325,000","207,000","160,000","183,000","244,000","208,000","213,000","414,000",nan
Tanzania,TZA,"285,000","315,000","347,000","450,000","564,000","459,000","501,000","550,000","552,000",...,"692,000","750,000","695,000","754,000","843,000","1,043,000","1,063,000","1,113,000","1,104,000","1,233,000"
Thailand,THA,"6,952,000","7,244,000","7,294,000","7,843,000","8,651,000","9,579,000","10,133,000","10,873,000","10,082,000",...,"14,464,000","14,584,000","14,150,000","15,936,000","19,230,000","22,354,000","26,547,000","24,810,000","29,923,000","32,530,000"
Timor-Leste,TLS,nan,nan,nan,nan,nan,nan,nan,nan,nan,...,"22,000","36,000","44,000","40,000","51,000","58,000","79,000","60,000","62,000","66,000"
Togo,TGO,"53,000","58,000","92,000","69,000","70,000","60,000","57,000","58,000","61,000",...,"86,000","74,000","150,000","202,000","300,000","235,000","327,000","282,000","273,000","338,000"
Tonga,TON,"29,000","27,000","26,000","27,000","31,000","35,000","32,000","37,000","40,000",...,"46,000","50,000","45,700","47,100","46,000","47,400","48,200","50,400","53,800","59,100"
Trinidad and Tobago,TTO,"260,000","266,000","324,000","334,000","358,000","399,000","383,000","384,000","409,000",...,"449,000","437,000","419,000","388,000","431,000","455,000","434,000","412,000","440,000","410,000"
Tunisia,TUN,"4,120,000","3,885,000","4,263,000","4,718,000","4,832,000","5,058,000","5,387,000","5,064,000","5,114,000",...,"6,762,000","7,050,000","7,797,000","7,828,000","5,746,000","6,999,000","7,352,000","7,163,000","5,359,000","5,724,000"
Turkey,TUR,"7,083,000","7,966,000","9,040,000","8,960,000","6,893,000","9,586,000","10,783,000","12,790,000","13,341,000",...,"26,122,000","29,792,000","30,187,000","31,364,000","34,654,000","35,698,000","37,795,000","39,811,000","39,478,000","30,289,000"
Turkmenistan,TKM,"218,000","217,000","257,000","300,000",nan,"3,400","5,200","10,800","8,200",...,"8,200",nan,nan,nan,nan,nan,nan,nan,nan,nan
Turks and Caicos Islands,TCA,"79,000","88,000","93,000","111,000","121,000","152,000","166,000","155,000","164,000",...,"265,000","352,000","351,000","281,000","354,000","291,700","290,600","357,000","386,000","454,000"
Tuvalu,TUV,900,"1,000","1,000","1,000","1,100","1,100","1,100","1,300","1,400",...,"1,100","1,700","1,600","1,700","1,200","1,100","1,300","1,400","2,400","2,500"
Uganda,UGA,"160,000","174,000","175,000","195,000","189,000","193,000","205,000","254,000","305,000",...,"642,000","844,000","807,000","946,000","1,151,000","1,197,000","1,206,000","1,266,000","1,303,000","1,323,000"
Ukraine,UKR,"3,716,000","3,854,000","7,558,000","6,208,000","4,232,000","6,431,000","9,174,000","10,517,000","12,514,000",...,"23,122,000","25,449,000","20,798,000","21,203,000","21,415,000","23,013,000","24,671,000","12,712,000","12,428,000","13,333,000"
United Arab Emirates,ARE,"2,315,000","2,572,000","2,476,000","2,991,000","3,393,000","3,907,000","4,134,000","5,445,000","5,871,000",...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
United Kingdom,GBR,"21,719,000","22,936,000","23,215,000","23,710,000","23,341,000","23,212,000","20,982,000","22,307,000","22,787,000",...,"30,870,000","30,142,000","28,199,000","28,295,000","29,306,000","29,282,000","31,063,000","32,613,000","34,436,000","35,814,000"
United States,USA,"43,318,000","46,489,000","47,767,000","46,377,000","48,509,000","51,238,000","46,927,000","43,581,000","41,218,000",...,"56,135,000","58,007,000","55,103,000","60,010,000","62,821,000","66,657,000","69,995,000","75,022,000","77,465,000","75,608,000"
Uruguay,URY,"2,022,000","2,152,000","2,316,000","2,163,000","2,073,000","1,968,000","1,892,000","1,258,000","1,420,000",...,"1,753,000","1,938,000","2,055,000","2,353,000","2,857,000","2,695,000","2,683,000","2,682,000","2,773,000","3,037,000"
Uzbekistan,UZB,"92,000","173,000","960,000","811,000","487,000","302,000","345,000","332,000","231,000",...,"903,000","1,069,000","1,215,000","975,000",nan,nan,"1,969,000",nan,nan,nan
Vanuatu,VUT,"44,000","46,000","50,000","52,000","51,000","58,000","53,000","49,000","50,000",...,"81,000","90,500","100,700","97,200","94,000","108,200","110,000","109,000","90,000","95,100"
"Venezuela, RB",VEN,"700,000","759,000","814,000","685,000","587,000","469,000","584,000","432,000","337,000",...,"756,000","699,000","562,000","526,000","595,000","988,000","986,000","857,000","789,000","601,000"
Vietnam,VNM,"1,351,000","1,607,000","1,716,000","1,520,000","1,782,000","2,140,000","2,330,000","2,628,000","2,429,000",...,"4,229,000","4,236,000","3,747,000","5,050,000","6,014,000","6,848,000","7,572,000","7,874,000","7,944,000","10,013,000"
Virgin Islands (U.S.),VIR,"454,000","373,000","393,000","422,000","484,000","546,000","527,000","520,000","538,000",...,"587,000","574,000","563,000","572,000","567,000","620,000","590,000","615,000","642,000",nan
West Bank and Gaza,PSE,nan,"220,000","210,000","200,000","300,000","310,000","43,000","33,000","37,000",...,"264,000","387,000","396,000","522,000","449,000","490,000","545,000","556,000","432,000","400,000"
"Yemen, Rep.",YEM,"61,000","74,000","80,000","88,000","58,000","73,000","76,000","98,000","155,000",...,"948,000","1,023,000","1,028,000","1,025,000","829,000","874,000","990,000","1,017,500","366,700",nan
Zambia,ZMB,"163,000","264,000","341,000","362,000","404,000","457,000","492,000","565,000","413,000",...,"897,000","812,000","710,000","815,000","920,000","859,000","915,000","947,000","932,000","956,000"
Zimbabwe,ZWE,"1,416,000","1,597,000","1,336,000","2,090,000","2,250,000","1,967,000","2,217,000","2,041,000","2,256,000",...,"2,506,000","1,956,000","2,017,000","2,239,000","2,423,000","1,794,000","1,833,000","1,880,000","2,057,000","2,168,000"

The data range from 1995 to 2016.  We want to create two new columns: one for 1995-1999 and one from 2000-2016.  Let's call them 20thCent and 21stCent.

In [10]:
oldCent = ['1995','1995','1996','1997','1998','1999']
df2[df2.columns[6:22]]
df2['19thCent'] = df2[oldCent].sum(axis=1)
df2['20thCent'] = df2[df2.columns[6:22]].sum(axis=1)
df2

,Code,1995,1996,1997,1998,1999,2000,2001,2002,2003,...,2009,2010,2011,2012,2013,2014,2015,2016,19thCent,20thCent
Country_Name,,,,,,,,,,,,,,,,,,,,,
Afghanistan,AFG,nan,nan,nan,nan,nan,nan,nan,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,nan,0,0
Albania,ALB,"304,000","287,000","119,000","184,000","371,000","317,000","354,000","470,000","557,000",...,"1,711,000","2,191,000","2,469,000","3,156,000","2,857,000","3,341,000","3,784,000","4,070,000","1,569,000","25,846,000"
Algeria,DZA,"520,000","605,000","635,000","678,000","749,000","866,000","901,000","988,000","1,166,000",...,"1,912,000","2,070,000","2,395,000","2,634,000","2,733,000","2,301,000","1,710,000","2,039,000","3,707,000","27,506,000"
American Samoa,ASM,"34,000","35,000","26,000","36,000","41,000","44,000","36,000",nan,nan,...,"23,500","23,100","22,600","22,600","20,800","21,600","20,300","20,100","206,000","332,700"
Andorra,AND,nan,nan,nan,nan,"2,347,000","2,949,000","3,516,000","3,387,000","3,138,000",...,"1,830,000","1,808,000","2,242,000","2,238,000","2,328,000","2,363,000","2,663,000","2,831,000","2,347,000","40,146,000"
Angola,AGO,"9,000","21,000","45,000","52,000","45,000","51,000","67,000","91,000","107,000",...,"366,000","425,000","481,000","528,000","650,000","595,000","592,000","397,000","181,000","4,967,000"
Antigua and Barbuda,ATG,"220,000","228,000","240,000","234,000","232,000","207,000","215,000","218,000","239,000",...,"234,000","230,000","241,000","247,000","243,000","249,000","250,000","265,000","1,374,000","3,846,000"
Argentina,ARG,"2,289,000","2,614,000","2,764,000","3,012,000","2,898,000","2,909,000","2,620,000","2,820,000","2,995,000",...,"4,308,000","5,325,000","5,705,000","5,587,000","5,246,000","5,931,000","5,736,000","5,559,000","15,866,000","69,897,000"
Armenia,ARM,"12,000","13,000","23,000","32,000","41,000","45,000","123,000","162,000","206,000",...,"575,000","684,000","758,000","963,000","1,084,000","1,204,000","1,192,000","1,260,000","133,000","9,029,000"
Aruba,ABW,"619,000","641,000","650,000","647,000","683,000","721,000","691,000","643,000","642,000",...,"813,000","824,000","869,000","904,000","979,000","1,072,000","1,225,000","1,102,000","3,859,000","13,137,000"
Australia,AUS,"3,726,000","4,165,000","4,318,000","4,167,000","4,459,000","4,931,000","4,856,000","4,841,000","4,746,000",...,"5,490,000","5,790,000","5,771,000","6,032,000","6,382,000","6,884,000","7,444,000","8,263,000","24,561,000","90,643,000"
Austria,AUT,"17,173,000","17,090,000","16,647,000","17,352,000","17,467,000","17,982,000","18,180,000","18,611,000","19,078,000",...,"21,355,000","22,004,000","23,012,000","24,151,000","24,813,000","25,291,000","26,728,000","28,121,000","102,902,000","343,508,000"
Azerbaijan,AZE,nan,nan,nan,nan,nan,nan,nan,"576,000","768,000",...,"1,005,000","1,280,000","1,562,000","1,986,000","2,130,000","2,160,000","1,922,000","2,044,000",0,"17,528,000"
"Bahamas, The",BHS,"1,598,000","1,633,000","1,618,000","1,528,000","1,577,000","1,544,000","1,538,000","1,513,000","1,510,000",...,"1,327,000","1,370,000","1,346,000","1,422,000","1,366,000","1,427,000","1,484,000","1,482,000","9,552,000","23,608,000"
Bahrain,BHR,"2,311,000","1,988,000","2,600,000","2,898,000","3,280,000","3,869,000","4,388,000","4,831,000","4,844,000",...,"8,861,000","11,952,000","6,732,000","8,062,000","9,163,000","10,452,000","9,670,000","10,158,000","15,388,000","118,557,000"
Bangladesh,BGD,"156,000","166,000","182,000","172,000","173,000","199,000","207,000","207,000","245,000",...,"267,000","303,000","155,000","125,000","148,000","125,000",nan,nan,"1,005,000","3,416,000"
Barbados,BRB,"442,000","447,000","472,000","512,000","515,000","545,000","507,000","498,000","531,000",...,"519,000","532,000","568,000","536,000","509,000","521,000","592,000","632,000","2,830,000","8,664,000"
Belarus,BLR,"160,600","234,000","253,500","355,000","74,900","60,000","61,000","63,000","64,000",...,"95,000","119,300","116,000","6,129,900","6,241,800","5,374,900","4,385,600","9,423,500","1,238,600","23,153,000"
Belgium,BEL,"5,560,000","5,829,000","6,037,000","6,179,000","6,369,000","6,457,000","6,452,000","6,720,000","6,690,000",...,"6,815,000","7,186,000","7,494,000","7,560,000","7,684,000","7,887,000","8,355,000","7,481,000","35,534,000","113,962,000"
Belize,BLZ,"131,000","133,000","146,000","176,000","181,000","196,000","196,000","200,000","221,000",...,"232,000","242,000","250,000","277,000","294,000","321,000","341,000","386,000","898,000","3,981,000"
Benin,BEN,"138,000","143,000","148,000","152,000","80,000","96,000","88,000","72,000","175,000",...,"190,000","199,000","209,000","220,000","231,000","242,000","255,000","267,000","799,000","2,881,000"
Bermuda,BMU,"387,000","390,000","380,000","370,000","355,000","332,000","278,000","284,000","257,000",...,"236,000","232,000","236,000","232,000","236,000","224,000","220,000","244,000","2,269,000","4,178,000"
Bhutan,BTN,"4,800","5,200","5,400","6,200","7,200","7,600","6,400","5,600","6,300",...,"23,000","41,000","66,000","105,000","116,000","133,000","155,000","210,000","33,600","754,000"
Bolivia,BOL,"284,000","313,000","355,000","387,000","342,000","319,000","316,000","334,000","427,000",...,"599,000","679,000","711,000","798,000","798,000","871,000","882,000","959,000","1,965,000","9,426,000"
Bosnia and Herzegovina,BIH,nan,nan,"115,000","148,000","147,000","171,000","139,000","160,000","165,000",...,"311,000","365,000","392,000","439,000","529,000","536,000","678,000","777,000","410,000","5,176,000"
Botswana,BWA,"521,000","512,000","607,000","750,000","843,000","1,104,000","1,193,000","1,274,000","1,406,000",...,"1,721,000","1,973,000",nan,"1,614,000","1,544,000","1,966,000","1,528,000",nan,"3,754,000","23,583,000"
Brazil,BRA,"1,991,000","2,666,000","2,850,000","4,818,000","5,107,000","5,313,000","4,773,000","3,785,000","4,133,000",...,"4,802,000","5,161,000","5,433,000","5,677,000","5,813,000","6,430,000","6,306,000","6,578,000","19,423,000","82,871,000"
British Virgin Islands,VGB,"219,000","244,000","244,000","279,000","284,000","272,000","296,000","282,000","278,000",...,"309,000","330,000","338,000","351,000","366,000","386,000","393,000","408,000","1,489,000","5,302,000"
Brunei Darussalam,BRN,nan,nan,nan,nan,nan,nan,nan,nan,nan,...,"157,000","214,000","242,000","209,000","225,000","201,000","218,000","219,000",0,"2,274,000"
Bulgaria,BGR,"3,466,000","2,795,000","2,980,000","2,667,000","2,472,000","2,785,000","3,186,000","3,433,000","4,048,000",...,"5,739,000","6,047,000","6,328,000","6,541,000","6,898,000","7,311,000","7,099,000","8,252,000","17,846,000","84,971,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sweden,SWE,"2,310,000","2,376,000","2,388,000","2,573,000","2,595,000","3,828,000","4,108,000","4,276,000","4,268,000",...,"4,899,000","5,183,000","5,222,000","5,146,000","5,229,000","5,660,000","6,482,000","6,782,000","14,552,000","78,368,000"
Switzerland,CHE,"6,946,000","6,730,000","7,039,000","7,185,000","7,154,000","7,821,000","7,455,000","6,868,000","6,530,000",...,"8,294,000","8,628,000","8,534,000","8,566,000","8,967,000","9,158,000","9,305,000","9,205,000","42,000,000","122,274,000"
Syrian Arab Republic,SYR,"815,000","830,000","891,000","1,267,000","1,386,000","2,100,000","2,192,000","2,661,000","2,598,000",...,"6,092,000","8,546,000","5,070,000",nan,nan,nan,nan,nan,"6,004,000","50,048,000"
Tajikistan,TJK,nan,700,"2,100","3,200","4,500","7,700","5,200",nan,nan,...,"207,000","160,000","183,000","244,000","208,000","213,000","414,000",nan,"10,500","1,966,900"
Tanzania,TZA,"285,000","315,000","347,000","450,000","564,000","459,000","501,000","550,000","552,000",...,"695,000","754,000","843,000","1,043,000","1,063,000","1,113,000","1,104,000","1,233,000","2,246,000","11,897,000"
Thailand,THA,"6,952,000","7,244,000","7,294,000","7,843,000","8,651,000","9,579,000","10,133,000","10,873,000","10,082,000",...,"14,150,000","15,936,000","19,230,000","22,354,000","26,547,000","24,810,000","29,923,000","32,530,000","44,936,000","259,791,000"
Timor-Leste,TLS,nan,nan,nan,nan,nan,nan,nan,nan,nan,...,"44,000","40,000","51,000","58,000","79,000","60,000","62,000","66,000",0,"466,000"
Togo,TGO,"53,000","58,000","92,000","69,000","70,000","60,000","57,000","58,000","61,000",...,"150,000","202,000","300,000","235,000","327,000","282,000","273,000","338,000","395,000","2,423,000"
Tonga,TON,"29,000","27,000","26,000","27,000","31,000","35,000","32,000","37,000","40,000",...,"45,700","47,100","46,000","47,400","48,200","50,400","53,800","59,100","169,000","700,600"
Trinidad and Tobago,TTO,"260,000","266,000","324,000","334,000","358,000","399,000","383,000","384,000","409,000",...,"419,000","388,000","431,000","455,000","434,000","412,000","440,000","410,000","1,802,000","6,807,000"
Tunisia,TUN,"4,120,000","3,885,000","4,263,000","4,718,000","4,832,000","5,058,000","5,387,000","5,064,000","5,114,000",...,"7,797,000","7,828,000","5,746,000","6,999,000","7,352,000","7,163,000","5,359,000","5,724,000","25,938,000","101,605,000"
Turkey,TUR,"7,083,000","7,966,000","9,040,000","8,960,000","6,893,000","9,586,000","10,783,000","12,790,000","13,341,000",...,"30,187,000","31,364,000","34,654,000","35,698,000","37,795,000","39,811,000","39,478,000","30,289,000","47,025,000","407,416,000"
Turkmenistan,TKM,"218,000","217,000","257,000","300,000",nan,"3,400","5,200","10,800","8,200",...,nan,nan,nan,nan,nan,nan,nan,nan,"1,210,000","67,800"
Turks and Caicos Islands,TCA,"79,000","88,000","93,000","111,000","121,000","152,000","166,000","155,000","164,000",...,"351,000","281,000","354,000","291,700","290,600","357,000","386,000","454,000","571,000","4,162,300"
Tuvalu,TUV,900,"1,000","1,000","1,000","1,100","1,100","1,100","1,300","1,400",...,"1,600","1,700","1,200","1,100","1,300","1,400","2,400","2,500","5,900","21,900"
Uganda,UGA,"160,000","174,000","175,000","195,000","189,000","193,000","205,000","254,000","305,000",...,"807,000","946,000","1,151,000","1,197,000","1,206,000","1,266,000","1,303,000","1,323,000","1,053,000","11,838,000"
Ukraine,UKR,"3,716,000","3,854,000","7,558,000","6,208,000","4,232,000","6,431,000","9,174,000","10,517,000","12,514,000",...,"20,798,000","21,203,000","21,415,000","23,013,000","24,671,000","12,712,000","12,428,000","13,333,000","29,284,000","275,643,000"
United Arab Emirates,ARE,"2,315,000","2,572,000","2,476,000","2,991,000","3,393,000","3,907,000","4,134,000","5,445,000","5,871,000",...,nan,nan,nan,nan,nan,nan,nan,nan,"16,062,000","32,678,000"
United Kingdom,GBR,"21,719,000","22,936,000","23,215,000","23,710,000","23,341,000","23,212,000","20,982,000","22,307,000","22,787,000",...,"28,199,000","28,295,000","29,306,000","29,282,000","31,063,000","32,613,000","34,436,000","35,814,000","136,640,000","447,865,000"
United States,USA,"43,318,000","46,489,000","47,767,000","46,377,000","48,509,000","51,238,000","46,927,000","43,581,000","41,218,000",...,"55,103,000","60,010,000","62,821,000","66,657,000","69,995,000","75,022,000","77,465,000","75,608,000","275,778,000","910,448,000"
Uruguay,URY,"2,022,000","2,152,000","2,316,000","2,163,000","2,073,000","1,968,000","1,892,000","1,258,000","1,420,000",...,"2,055,000","2,353,000","2,857,000","2,695,000","2,683,000","2,682,000","2,773,000","3,037,000","12,748,000","33,640,000"
Uzbekistan,UZB,"92,000","173,000","960,000","811,000","487,000","302,000","345,000","332,000","231,000",...,"1,215,000","975,000",nan,nan,"1,969,000",nan,nan,nan,"2,615,000","8,405,000"
Vanuatu,VUT,"44,000","46,000","50,000","52,000","51,000","58,000","53,000","49,000","50,000",...,"100,700","97,200","94,000","108,200","110,000","109,000","90,000","95,100","287,000","1,281,600"
"Venezuela, RB",VEN,"700,000","759,000","814,000","685,000","587,000","469,000","584,000","432,000","337,000",...,"562,000","526,000","595,000","988,000","986,000","857,000","789,000","601,000","4,245,000","10,520,000"
Vietnam,VNM,"1,351,000","1,607,000","1,716,000","1,520,000","1,782,000","2,140,000","2,330,000","2,628,000","2,429,000",...,"3,747,000","5,050,000","6,014,000","6,848,000","7,572,000","7,874,000","7,944,000","10,013,000","9,327,000","73,029,000"
Virgin Islands (U.S.),VIR,"454,000","373,000","393,000","422,000","484,000","546,000","527,000","520,000","538,000",...,"563,000","572,000","567,000","620,000","590,000","615,000","642,000",nan,"2,580,000","9,189,000"
West Bank and Gaza,PSE,nan,"220,000","210,000","200,000","300,000","310,000","43,000","33,000","37,000",...,"396,000","522,000","449,000","490,000","545,000","556,000","432,000","400,000","930,000","4,731,000"
"Yemen, Rep.",YEM,"61,000","74,000","80,000","88,000","58,000","73,000","76,000","98,000","155,000",...,"1,028,000","1,025,000","829,000","874,000","990,000","1,017,500","366,700",nan,"422,000","10,174,200"
Zambia,ZMB,"163,000","264,000","341,000","362,000","404,000","457,000","492,000","565,000","413,000",...,"710,000","815,000","920,000","859,000","915,000","947,000","932,000","956,000","1,697,000","11,675,000"
Zimbabwe,ZWE,"1,416,000","1,597,000","1,336,000","2,090,000","2,250,000","1,967,000","2,217,000","2,041,000","2,256,000",...,"2,017,000","2,239,000","2,423,000","1,794,000","1,833,000","1,880,000","2,057,000","2,168,000","10,105,000","32,886,000"

What are the numbers of travellers to Angola for each year between 1998-2002 inclusive?

In [11]:
df2.iloc[5,4:9]

1998   52,000
1999   45,000
2000   51,000
2001   67,000
2002   91,000
Name: Angola, dtype: object

List the countries in ascending order of their change in travellers between 1995-2015.
It might be more useful upon seeing the output to categorize the countries into 10 or so bix (given the range of the data, from 0 to almost 1,000,000,000) ...  Once you've made the bins, take another look and write a function to change any NaN values into something, such as 0.03, so there's a known error throughout the dataset and preventing any division or multiplication of 0.

In [13]:
bins = [0, 100000000,200000000,300000000,400000000,500000000,600000000,700000000,800000000,900000000,1000000000]
labels = ['1','2','3','4','5','6','7','8','9','10']
def fixNan(dataframe, colName): 
    if (colName == "nan"):
        colName = 0.03

fixNan('df2','20thCent')
df2

,Code,1995,1996,1997,1998,1999,2000,2001,2002,2003,...,2009,2010,2011,2012,2013,2014,2015,2016,19thCent,20thCent
Country_Name,,,,,,,,,,,,,,,,,,,,,
Afghanistan,AFG,nan,nan,nan,nan,nan,nan,nan,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,nan,0,0
Albania,ALB,"304,000","287,000","119,000","184,000","371,000","317,000","354,000","470,000","557,000",...,"1,711,000","2,191,000","2,469,000","3,156,000","2,857,000","3,341,000","3,784,000","4,070,000","1,569,000","25,846,000"
Algeria,DZA,"520,000","605,000","635,000","678,000","749,000","866,000","901,000","988,000","1,166,000",...,"1,912,000","2,070,000","2,395,000","2,634,000","2,733,000","2,301,000","1,710,000","2,039,000","3,707,000","27,506,000"
American Samoa,ASM,"34,000","35,000","26,000","36,000","41,000","44,000","36,000",nan,nan,...,"23,500","23,100","22,600","22,600","20,800","21,600","20,300","20,100","206,000","332,700"
Andorra,AND,nan,nan,nan,nan,"2,347,000","2,949,000","3,516,000","3,387,000","3,138,000",...,"1,830,000","1,808,000","2,242,000","2,238,000","2,328,000","2,363,000","2,663,000","2,831,000","2,347,000","40,146,000"
Angola,AGO,"9,000","21,000","45,000","52,000","45,000","51,000","67,000","91,000","107,000",...,"366,000","425,000","481,000","528,000","650,000","595,000","592,000","397,000","181,000","4,967,000"
Antigua and Barbuda,ATG,"220,000","228,000","240,000","234,000","232,000","207,000","215,000","218,000","239,000",...,"234,000","230,000","241,000","247,000","243,000","249,000","250,000","265,000","1,374,000","3,846,000"
Argentina,ARG,"2,289,000","2,614,000","2,764,000","3,012,000","2,898,000","2,909,000","2,620,000","2,820,000","2,995,000",...,"4,308,000","5,325,000","5,705,000","5,587,000","5,246,000","5,931,000","5,736,000","5,559,000","15,866,000","69,897,000"
Armenia,ARM,"12,000","13,000","23,000","32,000","41,000","45,000","123,000","162,000","206,000",...,"575,000","684,000","758,000","963,000","1,084,000","1,204,000","1,192,000","1,260,000","133,000","9,029,000"
Aruba,ABW,"619,000","641,000","650,000","647,000","683,000","721,000","691,000","643,000","642,000",...,"813,000","824,000","869,000","904,000","979,000","1,072,000","1,225,000","1,102,000","3,859,000","13,137,000"
Australia,AUS,"3,726,000","4,165,000","4,318,000","4,167,000","4,459,000","4,931,000","4,856,000","4,841,000","4,746,000",...,"5,490,000","5,790,000","5,771,000","6,032,000","6,382,000","6,884,000","7,444,000","8,263,000","24,561,000","90,643,000"
Austria,AUT,"17,173,000","17,090,000","16,647,000","17,352,000","17,467,000","17,982,000","18,180,000","18,611,000","19,078,000",...,"21,355,000","22,004,000","23,012,000","24,151,000","24,813,000","25,291,000","26,728,000","28,121,000","102,902,000","343,508,000"
Azerbaijan,AZE,nan,nan,nan,nan,nan,nan,nan,"576,000","768,000",...,"1,005,000","1,280,000","1,562,000","1,986,000","2,130,000","2,160,000","1,922,000","2,044,000",0,"17,528,000"
"Bahamas, The",BHS,"1,598,000","1,633,000","1,618,000","1,528,000","1,577,000","1,544,000","1,538,000","1,513,000","1,510,000",...,"1,327,000","1,370,000","1,346,000","1,422,000","1,366,000","1,427,000","1,484,000","1,482,000","9,552,000","23,608,000"
Bahrain,BHR,"2,311,000","1,988,000","2,600,000","2,898,000","3,280,000","3,869,000","4,388,000","4,831,000","4,844,000",...,"8,861,000","11,952,000","6,732,000","8,062,000","9,163,000","10,452,000","9,670,000","10,158,000","15,388,000","118,557,000"
Bangladesh,BGD,"156,000","166,000","182,000","172,000","173,000","199,000","207,000","207,000","245,000",...,"267,000","303,000","155,000","125,000","148,000","125,000",nan,nan,"1,005,000","3,416,000"
Barbados,BRB,"442,000","447,000","472,000","512,000","515,000","545,000","507,000","498,000","531,000",...,"519,000","532,000","568,000","536,000","509,000","521,000","592,000","632,000","2,830,000","8,664,000"
Belarus,BLR,"160,600","234,000","253,500","355,000","74,900","60,000","61,000","63,000","64,000",...,"95,000","119,300","116,000","6,129,900","6,241,800","5,374,900","4,385,600","9,423,500","1,238,600","23,153,000"
Belgium,BEL,"5,560,000","5,829,000","6,037,000","6,179,000","6,369,000","6,457,000","6,452,000","6,720,000","6,690,000",...,"6,815,000","7,186,000","7,494,000","7,560,000","7,684,000","7,887,000","8,355,000","7,481,000","35,534,000","113,962,000"
Belize,BLZ,"131,000","133,000","146,000","176,000","181,000","196,000","196,000","200,000","221,000",...,"232,000","242,000","250,000","277,000","294,000","321,000","341,000","386,000","898,000","3,981,000"
Benin,BEN,"138,000","143,000","148,000","152,000","80,000","96,000","88,000","72,000","175,000",...,"190,000","199,000","209,000","220,000","231,000","242,000","255,000","267,000","799,000","2,881,000"
Bermuda,BMU,"387,000","390,000","380,000","370,000","355,000","332,000","278,000","284,000","257,000",...,"236,000","232,000","236,000","232,000","236,000","224,000","220,000","244,000","2,269,000","4,178,000"
Bhutan,BTN,"4,800","5,200","5,400","6,200","7,200","7,600","6,400","5,600","6,300",...,"23,000","41,000","66,000","105,000","116,000","133,000","155,000","210,000","33,600","754,000"
Bolivia,BOL,"284,000","313,000","355,000","387,000","342,000","319,000","316,000","334,000","427,000",...,"599,000","679,000","711,000","798,000","798,000","871,000","882,000","959,000","1,965,000","9,426,000"
Bosnia and Herzegovina,BIH,nan,nan,"115,000","148,000","147,000","171,000","139,000","160,000","165,000",...,"311,000","365,000","392,000","439,000","529,000","536,000","678,000","777,000","410,000","5,176,000"
Botswana,BWA,"521,000","512,000","607,000","750,000","843,000","1,104,000","1,193,000","1,274,000","1,406,000",...,"1,721,000","1,973,000",nan,"1,614,000","1,544,000","1,966,000","1,528,000",nan,"3,754,000","23,583,000"
Brazil,BRA,"1,991,000","2,666,000","2,850,000","4,818,000","5,107,000","5,313,000","4,773,000","3,785,000","4,133,000",...,"4,802,000","5,161,000","5,433,000","5,677,000","5,813,000","6,430,000","6,306,000","6,578,000","19,423,000","82,871,000"
British Virgin Islands,VGB,"219,000","244,000","244,000","279,000","284,000","272,000","296,000","282,000","278,000",...,"309,000","330,000","338,000","351,000","366,000","386,000","393,000","408,000","1,489,000","5,302,000"
Brunei Darussalam,BRN,nan,nan,nan,nan,nan,nan,nan,nan,nan,...,"157,000","214,000","242,000","209,000","225,000","201,000","218,000","219,000",0,"2,274,000"
Bulgaria,BGR,"3,466,000","2,795,000","2,980,000","2,667,000","2,472,000","2,785,000","3,186,000","3,433,000","4,048,000",...,"5,739,000","6,047,000","6,328,000","6,541,000","6,898,000","7,311,000","7,099,000","8,252,000","17,846,000","84,971,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sweden,SWE,"2,310,000","2,376,000","2,388,000","2,573,000","2,595,000","3,828,000","4,108,000","4,276,000","4,268,000",...,"4,899,000","5,183,000","5,222,000","5,146,000","5,229,000","5,660,000","6,482,000","6,782,000","14,552,000","78,368,000"
Switzerland,CHE,"6,946,000","6,730,000","7,039,000","7,185,000","7,154,000","7,821,000","7,455,000","6,868,000","6,530,000",...,"8,294,000","8,628,000","8,534,000","8,566,000","8,967,000","9,158,000","9,305,000","9,205,000","42,000,000","122,274,000"
Syrian Arab Republic,SYR,"815,000","830,000","891,000","1,267,000","1,386,000","2,100,000","2,192,000","2,661,000","2,598,000",...,"6,092,000","8,546,000","5,070,000",nan,nan,nan,nan,nan,"6,004,000","50,048,000"
Tajikistan,TJK,nan,700,"2,100","3,200","4,500","7,700","5,200",nan,nan,...,"207,000","160,000","183,000","244,000","208,000","213,000","414,000",nan,"10,500","1,966,900"
Tanzania,TZA,"285,000","315,000","347,000","450,000","564,000","459,000","501,000","550,000","552,000",...,"695,000","754,000","843,000","1,043,000","1,063,000","1,113,000","1,104,000","1,233,000","2,246,000","11,897,000"
Thailand,THA,"6,952,000","7,244,000","7,294,000","7,843,000","8,651,000","9,579,000","10,133,000","10,873,000","10,082,000",...,"14,150,000","15,936,000","19,230,000","22,354,000","26,547,000","24,810,000","29,923,000","32,530,000","44,936,000","259,791,000"
Timor-Leste,TLS,nan,nan,nan,nan,nan,nan,nan,nan,nan,...,"44,000","40,000","51,000","58,000","79,000","60,000","62,000","66,000",0,"466,000"
Togo,TGO,"53,000","58,000","92,000","69,000","70,000","60,000","57,000","58,000","61,000",...,"150,000","202,000","300,000","235,000","327,000","282,000","273,000","338,000","395,000","2,423,000"
Tonga,TON,"29,000","27,000","26,000","27,000","31,000","35,000","32,000","37,000","40,000",...,"45,700","47,100","46,000","47,400","48,200","50,400","53,800","59,100","169,000","700,600"
Trinidad and Tobago,TTO,"260,000","266,000","324,000","334,000","358,000","399,000","383,000","384,000","409,000",...,"419,000","388,000","431,000","455,000","434,000","412,000","440,000","410,000","1,802,000","6,807,000"
Tunisia,TUN,"4,120,000","3,885,000","4,263,000","4,718,000","4,832,000","5,058,000","5,387,000","5,064,000","5,114,000",...,"7,797,000","7,828,000","5,746,000","6,999,000","7,352,000","7,163,000","5,359,000","5,724,000","25,938,000","101,605,000"
Turkey,TUR,"7,083,000","7,966,000","9,040,000","8,960,000","6,893,000","9,586,000","10,783,000","12,790,000","13,341,000",...,"30,187,000","31,364,000","34,654,000","35,698,000","37,795,000","39,811,000","39,478,000","30,289,000","47,025,000","407,416,000"
Turkmenistan,TKM,"218,000","217,000","257,000","300,000",nan,"3,400","5,200","10,800","8,200",...,nan,nan,nan,nan,nan,nan,nan,nan,"1,210,000","67,800"
Turks and Caicos Islands,TCA,"79,000","88,000","93,000","111,000","121,000","152,000","166,000","155,000","164,000",...,"351,000","281,000","354,000","291,700","290,600","357,000","386,000","454,000","571,000","4,162,300"
Tuvalu,TUV,900,"1,000","1,000","1,000","1,100","1,100","1,100","1,300","1,400",...,"1,600","1,700","1,200","1,100","1,300","1,400","2,400","2,500","5,900","21,900"
Uganda,UGA,"160,000","174,000","175,000","195,000","189,000","193,000","205,000","254,000","305,000",...,"807,000","946,000","1,151,000","1,197,000","1,206,000","1,266,000","1,303,000","1,323,000","1,053,000","11,838,000"
Ukraine,UKR,"3,716,000","3,854,000","7,558,000","6,208,000","4,232,000","6,431,000","9,174,000","10,517,000","12,514,000",...,"20,798,000","21,203,000","21,415,000","23,013,000","24,671,000","12,712,000","12,428,000","13,333,000","29,284,000","275,643,000"
United Arab Emirates,ARE,"2,315,000","2,572,000","2,476,000","2,991,000","3,393,000","3,907,000","4,134,000","5,445,000","5,871,000",...,nan,nan,nan,nan,nan,nan,nan,nan,"16,062,000","32,678,000"
United Kingdom,GBR,"21,719,000","22,936,000","23,215,000","23,710,000","23,341,000","23,212,000","20,982,000","22,307,000","22,787,000",...,"28,199,000","28,295,000","29,306,000","29,282,000","31,063,000","32,613,000","34,436,000","35,814,000","136,640,000","447,865,000"
United States,USA,"43,318,000","46,489,000","47,767,000","46,377,000","48,509,000","51,238,000","46,927,000","43,581,000","41,218,000",...,"55,103,000","60,010,000","62,821,000","66,657,000","69,995,000","75,022,000","77,465,000","75,608,000","275,778,000","910,448,000"
Uruguay,URY,"2,022,000","2,152,000","2,316,000","2,163,000","2,073,000","1,968,000","1,892,000","1,258,000","1,420,000",...,"2,055,000","2,353,000","2,857,000","2,695,000","2,683,000","2,682,000","2,773,000","3,037,000","12,748,000","33,640,000"
Uzbekistan,UZB,"92,000","173,000","960,000","811,000","487,000","302,000","345,000","332,000","231,000",...,"1,215,000","975,000",nan,nan,"1,969,000",nan,nan,nan,"2,615,000","8,405,000"
Vanuatu,VUT,"44,000","46,000","50,000","52,000","51,000","58,000","53,000","49,000","50,000",...,"100,700","97,200","94,000","108,200","110,000","109,000","90,000","95,100","287,000","1,281,600"
"Venezuela, RB",VEN,"700,000","759,000","814,000","685,000","587,000","469,000","584,000","432,000","337,000",...,"562,000","526,000","595,000","988,000","986,000","857,000","789,000","601,000","4,245,000","10,520,000"
Vietnam,VNM,"1,351,000","1,607,000","1,716,000","1,520,000","1,782,000","2,140,000","2,330,000","2,628,000","2,429,000",...,"3,747,000","5,050,000","6,014,000","6,848,000","7,572,000","7,874,000","7,944,000","10,013,000","9,327,000","73,029,000"
Virgin Islands (U.S.),VIR,"454,000","373,000","393,000","422,000","484,000","546,000","527,000","520,000","538,000",...,"563,000","572,000","567,000","620,000","590,000","615,000","642,000",nan,"2,580,000","9,189,000"
West Bank and Gaza,PSE,nan,"220,000","210,000","200,000","300,000","310,000","43,000","33,000","37,000",...,"396,000","522,000","449,000","490,000","545,000","556,000","432,000","400,000","930,000","4,731,000"
"Yemen, Rep.",YEM,"61,000","74,000","80,000","88,000","58,000","73,000","76,000","98,000","155,000",...,"1,028,000","1,025,000","829,000","874,000","990,000","1,017,500","366,700",nan,"422,000","10,174,200"
Zambia,ZMB,"163,000","264,000","341,000","362,000","404,000","457,000","492,000","565,000","413,000",...,"710,000","815,000","920,000","859,000","915,000","947,000","932,000","956,000","1,697,000","11,675,000"
Zimbabwe,ZWE,"1,416,000","1,597,000","1,336,000","2,090,000","2,250,000","1,967,000","2,217,000","2,041,000","2,256,000",...,"2,017,000","2,239,000","2,423,000","1,794,000","1,833,000","1,880,000","2,057,000","2,168,000","10,105,000","32,886,000"